app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis
    ports:
        - "8000:8000"
    volumes:
        - "./requestbin:/opt/requestbin/requestbin"

redis:
    image: redis
