namespace: ads
productgroup: cpi-direct

enableDeployment: true
deployment:
  image:
    repository: gcr.io/unity-ads-common-prd/requestbin
    tag: master

  replicas: 1

  nodeSelector:
    kind: standard-pool

  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"

  tolerations:
    - key: "machine_type"
      operator: "Equal"
      value: "standard"
      effect: "NoSchedule"

  resources:
    requests:
      cpu: 1
      memory: 200Mi
    noLimits: true

  livenessProbe:
    httpGet:
      path: /ready
      port: 8000
      scheme: HTTPS

  readinessProbe:
    httpGet:
      path: /ready
      port: 8000
      scheme: HTTPS

  ports:
    - containerPort: 8000
      protocol: TCP

enableService: true
service:
  type: ClusterIP
  ports:
    - name: requestbin-https
      protocol: TCP
      port: 443
      targetPort: 8000
