namespace: ads
productgroup: cpi-direct

enableDeployment: true
deployment:
  image:
    repository: gcr.io/unity-ads-common-prd/requestbin
    tag: master

  replicas: 1

  nodeSelector:
    kind: standard-pool

  tolerations:
    - key: "machine_type"
      operator: "Equal"
      value: "standard"
      effect: "NoSchedule"

  resources:
    requests:
      cpu: 1
      memory: 200Mi
    noLimits: true

  ports:
    - name: http
      containerPort: 8000
      protocol: TCP

  livenessProbe:
    httpGet:
      path: /ready
      port: http
      scheme: HTTPS

  readinessProbe:
    httpGet:
      path: /ready
      port: http
      scheme: HTTPS

enableService: true
service:
  type: NodePort
  ports:
    - name: requestbin-https
      protocol: TCP
      port: 443
      targetPort: http

enableIngress: true
ingress:
  host: requestbin.stg.mz.internal.unity3d.com
  secretName: tls-stg-mz-internal-unity3d-com
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "requestbin-ingress"
    kubernetes.io/ingress.allow-http: "false"
  paths:
    - '/*'

enableBackendConfig: true
backendConfig:
  securityPolicy: unity-internal

